blog/urls.py
from django.urls import path

from .views import PostDetailView, meet_create, post_create, meet_detail, MeetListView, PostListView

app_name = 'blog'

urlpatterns = [
    path('meets/create', meet_create, name='meet-create'),
    path('meets/<int:pk>/', meet_detail, name='meet-detail'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('meets/', MeetListView.as_view(), name='meet-list'),
    path('posts/', PostListView.as_view(), name='post-list'),
    path('posts/create/', post_create, name='post-create'),
]

core/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from rest_framework_swagger.views import get_swagger_view
from users.views import already_logined
from . import settings
from django.views.static import serve


schema_view = get_swagger_view(title='Pastebin API')

api_urlpatterns = [
    path('api/', include('blog.api.urls')),
    path('api/', include('chat.api.urls')),
    path('api/', include('users.api.urls')),

]

urlpatterns = [
                  path('', TemplateView.as_view(template_name='home.html'), name='home'),
                  path('logined_already', already_logined, name='already-logined'),
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('', include('users.urls')),
                  # path('chat/', include('chat.urls')),
                  path('swag/', schema_view),
                  re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
                  re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

              ] + api_urlpatterns

# if settings.DEBUG:

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.e_handler404'
handler500 = 'blog.views.e_handler500'

users/api/urls.py
from django.urls import path
from rest_framework import routers

from blog.api.views import PostViewSet, TagViewSet

# from users.api.views import UserViewSet
from users.api.tokens import TokenCreate, TokenRefresh
from users.api.views import follow_user

app_name = 'api'

router = routers.DefaultRouter()
# router.register('users', UserViewSet, basename='user-api')

urlpatterns = [
    # path('users/<int:pk>', UserRetrieveView.as_view(), name='user'),
    path('token/', TokenCreate.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefresh.as_view(), name='token_refresh'),
    path('users/follow/<int:pk>', follow_user, name='user-follow'),
] + router.urls

users/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path
from users.views import signup, activate, Reset, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView, SignInnView, change_user, UserDetailView

app_name = 'users'

urlpatterns = [
    re_path(r'^signup/$', signup, name='signup'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            activate, name='activate'),
    path('login/', SignInnView.as_view(), name='login'),
    path('change/', change_user, name='change'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),

    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('reset/', Reset.as_view(), name='reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _

# Create your models here.



class User(AbstractUser):
    follow = models.ManyToManyField('self', related_name='followers', null=True, blank=True, symmetrical=False)
    email = models.EmailField(_('email address'), unique=True)

    avatar = models.ImageField(upload_to='uploads/%Y/%m/%d/', null=True, blank=True
                               # , default='/static/avatar_default.png'
                               )


    # REQUIRED_FIELDS = ['email']

    def bookmark_post(self, post_id):
        try:
            self.bookmarks.get(id=post_id)
            self.bookmarks.remove(post_id)
        except Exception as e:
            self.bookmarks.add(post_id)

        return True

    def follow_user(self, user_id):
        try:
            self.follow.get(id=user_id)
            self.follow.remove(user_id)
        except Exception as e:
            self.follow.add(user_id)

    def get_absolute_url(self):
        return reverse_lazy('users:user-detail', args=[self.pk])

users/api/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response


# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = OtherUserSerializer
#     pagination_class = MyPaginator
    # filter_backends = (SearchFilter, OrderingFilter, PostTagFilter)
    # filterset_fields = ('author', 'title')
    # search_fields = ('title',)
    # ordering_fields = ('created',)
    # ordering = ('-created',)


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def follow_user(request, pk):
    user = request.user
    user.follow_user(pk)
    return Response (status=200)

users/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin, AccessMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView as passwordResetConfirmView, \
    PasswordResetDoneView as passwordResetDoneView, PasswordResetCompleteView as passwordResetCompleteView, \
    LoginView as loginView
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.generic import DetailView

from users.forms import SignupForm, PasswordRestForm, SetPasswordForm, SignInForm, UserChangeForm
from users.models import User
from users.tasks import send_register_confirmation_email
from users.tokens import account_activation_token


@user_passes_test(lambda user: user.is_anonymous,
                  login_url=reverse_lazy('already-logined'),
                  redirect_field_name=None)
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            domain = current_site.domain
            to_email = form.cleaned_data.get('email')
            send_register_confirmation_email.delay(user.pk, domain, to_email)

            return render(request, 'users/signup_confirm_sent.html')
    else:
        form = SignupForm()
    return render(request, 'users/signup.html', {'form': form})


@user_passes_test(lambda user: user.is_anonymous,
                  login_url=reverse_lazy('already-logined'),
                  redirect_field_name=None)
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # return redirect('home')
        return render(request, 'users/signup_activated.html')
    else:
        return render(request, 'users/signup_activated_fail.html')


@login_required(login_url=reverse_lazy('home'))
def already_logined(request):
    return render(request, 'already_logined.html')


class AnonymousRequiredMixin(AccessMixin):
    """Verify that the current user is authenticated."""

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def handle_no_permission(self):
        return redirect(reverse('already-logined'))


class SignInnView(AnonymousRequiredMixin, loginView):
    form_class = SignInForm
    template_name = 'users/login.html'
    redirect_authenticated_user = True
#     TODO next (REDIRECT_FIELD_NAME)


class Reset(PasswordResetView):
    form_class = PasswordRestForm
    template_name = 'users/password_reset.html'
    html_email_template_name = 'users/password_reset_email.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')


class PasswordResetConfirmView(passwordResetConfirmView):
    form_class = SetPasswordForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class PasswordResetDoneView(passwordResetDoneView):
    template_name = 'users/password_reset_done.html'


class PasswordResetCompleteView(passwordResetCompleteView):
    template_name = 'users/password_reset_complete.html'


def change_user(request):
    if request.method == 'POST':
        user = UserChangeForm(request.POST, request.FILES, instance=request.user)
        if user.is_valid():
            user = user.save()
            return  redirect(reverse('users:user-detail', args=[user.pk]))
        else:
            return render(request, 'users/user-change.html', {'form': user})
    user = request.user
    form = UserChangeForm(initial={
        'username': user.username,
        'email': user.email
    })
    return render(request, 'users/user-change.html', {'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'users/user-detail.html'

users/templates/users/acc_active_email.html
{% autoescape off %}
<h3>Hi {{ username }},
Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}</h3>
{% endautoescape %}

users/templates/users/logged_out.html
{% extends 'base.html' %}

{% block content %}

    <h2>Now you're logged out! <a href="{% url 'home' %}">Home</a> page</h2>

{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h2>Login</h2>

    {% crispy form %}
{% endblock %}

users/templates/users/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h2>Reset password</h2>

    {% crispy form %}
    {#    <div id='form-errors'>{{ form_errors }}</div>#}
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <h3>{% trans "Your password has been set.  You may go ahead and log in now." %}</h3>

    <h3><a href="{{ login_url }}">{% trans 'Log in' %}</a></h3>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h2>Set new password</h2>

    {% crispy form %}
    {#    <div id='form-errors'>{{ form_errors }}</div>#}
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <h3>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</h3>

    <h3>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</h3>

    <h3>Go <a href="{% url 'home' %}">home</a></h3>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
    {% blocktrans %}<h1>You're receiving this email because you requested a password reset for your user account
        at {{ site_name }}.</h1>{% endblocktrans %}

    <h3>{% trans "Please go to the following page and choose a new password:" %}</h3>
    <h3>
        {% block reset_link %}
            {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
        {% endblock %}
    </h3>
    <h3>
        {% trans "Your username, in case you've forgotten:" %} {{ username }}
    </h3>
    <h3>
        {% trans "Thanks for using our site!" %}
    </h3>
    <h3>
        {% blocktrans %}The {{ site_name }} team{% endblocktrans %}
    </h3>
{% endautoescape %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h2>Sign up</h2>

    {% crispy form %}
{% endblock %}


{#  <form method="post">#}
{#    {% csrf_token %}#}
{#      {% for field in form %}#}
{#      <p>#}
{#        {{ field.label_tag }}<br>#}
{#        {{ field }}#}
{#        {% if field.help_text %}#}
{#          <small style="display: none">{{ field.help_text }}</small>#}
{#        {% endif %}#}
{#        {% for error in field.errors %}#}
{#          <p style="color: red">{{ error }}</p>#}
{#        {% endfor %}#}
{#      </p>#}
{#      {% endfor %}#}
{#    <button type="submit">Sign up</button>#}
{#  </form>#}

users/templates/users/signup_activated.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h2>Thank you for your email confirmation. Now you can login your account.</h2>

{% endblock %}

users/templates/users/signup_activated_fail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h2>Activation link is invalid!</h2>

{% endblock %}

users/templates/users/signup_confirm_sent.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h2>Please confirm your email address (if it exists) to complete the registration</h2>

{% endblock %}

users/templates/users/user-change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h2>Change user</h2>

    {% crispy form %}
{% endblock %}

users/templates/users/user-detail.html
{% extends 'base.html' %}
{#{% load crispy_forms_tags %}#}

{% block content %}


    <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">

          <div class="col-lg-4 offset-md-3  ">
            <img class="rounded-circle" src="{{ user.avatar.url }}" alt="Generic placeholder image" width="140" height="140">
            <h2>{{ user.username }}</h2>
            <p>{{ user.email }}</p>
              {% if user.id == request.user.id %}
            <p><a class="btn btn-primary" href="{% url 'users:change' %}" role="button">Change</a></p>
              {% endif %}
          </div><!-- /.col-lg-4 -->

        </div>

        <!-- START THE FEATURETTES -->




      </div>

{% endblock %}