blog/urls.py
from django.urls import path

from .views import PostDetailView, meet_create, post_create, meet_detail, MeetListView, PostListView

app_name = 'blog'

urlpatterns = [
    path('meets/create', meet_create, name='meet-create'),
    path('meets/<int:pk>/', meet_detail, name='meet-detail'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('meets/', MeetListView.as_view(), name='meet-list'),
    path('posts/', PostListView.as_view(), name='post-list'),
    path('posts/create/', post_create, name='post-create'),
]

core/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from rest_framework_swagger.views import get_swagger_view
from users.views import already_logined
from . import settings
from django.views.static import serve


schema_view = get_swagger_view(title='Pastebin API')

api_urlpatterns = [
    path('api/', include('blog.api.urls')),
    path('api/', include('chat.api.urls')),
    path('api/', include('users.api.urls')),

]

urlpatterns = [
                  path('', TemplateView.as_view(template_name='home.html'), name='home'),
                  path('logined_already', already_logined, name='already-logined'),
                  path('admin/', admin.site.urls),
                  path('', include('blog.urls')),
                  path('', include('users.urls')),
                  # path('chat/', include('chat.urls')),
                  path('swag/', schema_view),
                  re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
                  re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

              ] + api_urlpatterns

# if settings.DEBUG:

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'blog.views.e_handler404'
handler500 = 'blog.views.e_handler500'

users/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, re_path
from users.views import signup, activate, Reset, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView, SignInnView, change_user, UserDetailView

app_name = 'users'

urlpatterns = [
    re_path(r'^signup/$', signup, name='signup'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            activate, name='activate'),
    path('login/', SignInnView.as_view(), name='login'),
    path('change/', change_user, name='change'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),

    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('reset/', Reset.as_view(), name='reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

templates/already_logined.html
{% extends 'base.html' %}

{% block content %}

    <h2>U've already logged in go <a href="{% url 'home' %}">home</a></h2>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>#}
    <script src="{% static 'js/3.4.1_jquery.js' %}"></script>
    <script src="{% static 'js/general.js' %}"></script>
    <script src="{% static 'js/reconnecting-websocket.min.js' %}"></script>

    {#    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>#}
    {#    <script src="https://unpkg.com/@google/markerclustererplus@4.0.1/dist/markerclustererplus.min.js"></script>#}

    {% block links %}

    {% endblock %}

</head>
<header>

</header>
<body>

{% include 'header.html' %}

<div class="container" style="min-height:700px">

    {% block content %}{% endblock %}

</div>

{% include 'footer.html' %}


<script>

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

</script>

{% block js %}{% endblock %}

</body>
</html>

templates/footer.html
{% load static %}

<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">Green+</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0"></ul>
        <a class="nav-link text-light" href="{% url 'home' %}">Home</a>
            {% if request.user.is_authenticated %}
        <a class="text-light btn my-2 my-sm-0 bg-success" href="{% url 'users:logout' %}" type="submit">
            Logout
            {% else %}
        <a class="text-light btn my-2 my-sm-0 bg-success btn-link" href="{% url 'users:login' %}" type="submit">
            Login
            {% endif %}
        </a>
    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block content %}

    {#  <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/images/43.jpg" alt="Card image cap">#}

    <div class="row">
        <div class="col-sm-6 mt-4">
            <div class="card  h-100">

                <div class="card-body">
                    <h5 class="card-title">Sign Up</h5>
{#                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to#}
{#                        additional content. This content is a little bit longer.</p>#}
{#                    <p class="card-text"><small class="text-muted"> Last updated 3 mins ago</small></p>#}
                    <a href="{% url 'users:signup' %}"
                       class="btn btn-primary stretched-link">Go</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mt-4">
            <div class="card  h-100">

                <div class="card-body">
                    <h5 class="card-title">Create Meet</h5>
{#                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to#}
{#                        additional content. This content is a little bit longer.</p>#}
{#                    <p class="card-text"><small class="text-muted"> Last updated 3 mins ago</small></p>#}
                    <a href="{% url 'blog:meet-create' %}"
                       class="btn btn-primary stretched-link">Go</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mt-4">
            <div class="card  h-100">

                <div class="card-body">
                    <h5 class="card-title">Create Post</h5>
{#                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to#}
{#                        additional content. This content is a little bit longer.</p>#}
{#                    <p class="card-text"><small class="text-muted"> Last updated 3 mins ago</small></p>#}
                    <a href="{% url 'blog:post-create' %}"
                       class="btn btn-primary stretched-link">Go</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mt-4">
            <div class="card  h-100">

                <div class="card-body">
                    <h5 class="card-title">Reset Password</h5>
{#                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to#}
{#                        additional content. This content is a little bit longer.</p>#}
{#                    <p class="card-text"><small class="text-muted"> Last updated 3 mins ago</small></p>#}
                    <a href="{% url 'users:reset' %}"
                       class="btn btn-primary stretched-link">Go</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mt-4">
            <div class="card  h-100">

                <div class="card-body">
                    <h5 class="card-title">Meets</h5>
{#                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to#}
{#                        additional content. This content is a little bit longer.</p>#}
{#                    <p class="card-text"><small class="text-muted"> Last updated 3 mins ago</small></p>#}
                    <a href="{% url 'blog:meet-list' %}"
                       class="btn btn-primary stretched-link">Go</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mt-4">
            <div class="card  h-100">

                <div class="card-body">
                    <h5 class="card-title">Posts</h5>
{#                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to#}
{#                        additional content. This content is a little bit longer.</p>#}
{#                    <p class="card-text"><small class="text-muted"> Last updated 3 mins ago</small></p>#}
                    <a href="{% url 'blog:post-list' %}"
                       class="btn btn-primary stretched-link">Go</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mt-4">
            <div class="card  h-100">

                <div class="card-body">
                    <h5 class="card-title">User change</h5>
{#                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to#}
{#                        additional content. This content is a little bit longer.</p>#}
{#                    <p class="card-text"><small class="text-muted"> Last updated 3 mins ago</small></p>#}
                    <a href="{% url 'users:change' %}"
                       class="btn btn-primary stretched-link">Go</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6 mt-4">
            <div class="card  h-100">

                <div class="card-body">
                    <h5 class="card-title">User page</h5>
{#                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to#}
{#                        additional content. This content is a little bit longer.</p>#}
{#                    <p class="card-text"><small class="text-muted"> Last updated 3 mins ago</small></p>#}
                    <a href="{% url 'users:change' %}"
                       class="btn btn-primary stretched-link">Go</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" media="screen"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}" media="screen"/>

    <script src="{% static 'js/3.4.1_jquery.js' %}"></script>
    <script src="{% static 'js/general.js' %}"></script>
    <script src="{% static 'js/reconnecting-websocket.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" media="screen"/>

</head>
<body>

<!-- POST-LIST -->

{% include 'header.html' %}

<div class="container">

    {% block content %}{% endblock %}

</div>

{% include 'footer.html' %}


{% block extra_js %}

    <script>

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        };

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

    </script>


{% endblock %}

</body>
</html>